---
title: "Assignment 1: Linear Models"
author: "YOUR NAME HERE"
format: 
  html:
    code-fold: true
    code-line-numbers: true
    code-tools: true
    embed-resources: true
editor: visual
---

```{r}
#| label: packages
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(broom)
```

## Step 1

```{r}
ins <- read_csv(here::here("path", "to", "your", "data.csv"))
```

## Step 2

#### Q1

```{r}
ins %>% 
  count()
```

#### Q2

```{r}
ins <- ins %>%
  mutate(
    #### your code here
  )
```

#### Q3

```{r}
### Code for scatter plot
ins %>%
  ggplot(mapping = aes(x = ???, y = ???, color = ???)) +
  geom_point()

### Code for boxplot
ins %>%
  ggplot(mapping = aes(x = ???, y = ???, fill = ???)) +
  geom_boxplot()
```

## Step 3

#### Q4

```{r}
lin_reg_spec <- linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")

ins_lm_fit <- lin_reg_spec %>%
  fit(_______, _______, data = ins) 
```

#### Q5

```{r}
# To get coefficient estimates, SEs, p-values, and CIs
tidy(ins_lm_fit) 
```

#### Q6

```{r}
# To model summary statistics
glance(ins_lm_fit)
```

#### Q7

#### Q8

#### Q9

#### Q10

#### Q11

#### Q12

## Step 4

#### Q13

#### Q14

#### Q15

#### Q16

#### Q17

#### Q18

#### Q19

#### Q20

#### Q21

```{r}
<YOUR DATASET> %>%
  ggplot() +
  geom_point(mapping = aes(x = age, y = charges)) +
  geom_line(mapping = aes(x = age, y = predicted_charges))

```

## Step 5

#### Q22

#### Q23

#### Q24

#### Q25
