---
title: "Assignment 1: Linear Models"
author: "Due Monday, October 2 at 5pm"
format: html
embed-resources: true
editor: visual
---

# Instructions

You will submit an HTML document to Canvas as your final version.

## Getting Started

[Download starter .qmd file](linear-regression-template.qmd)

You'll notice in the template's YAML there are specifications for how the code should be included (i.e., `code-fold: true`, `code-line-numbers: true`, `code-tools: true`). **Do not change these specifications.**

::: callout-caution
# Within your document make sure that only relevant output is printed

Do not, for example, print the preview (e.g., `head(data)`) or an entire dataset in your final knitted file.
:::

::: callout-tip
# Organization

Your document should also be clearly organized, so that it is easy for a reader to find your answers to each question. If I have a difficult time locating or reading your answer, you risk it being returned with a "revision requested".
:::

# Step 1: Download the Data

The dataset we will study for this assignment contains information about health insurance costs for individuals with no dependents (children) in the United States. The information contained in the data is:

-   Age of primary beneficiary

-   Biological sex of primary beneficiary (recorded as gender)

-   Body mass index, providing an understanding of body, weights that are relatively high or low relative to height, objective index of body weight (kg / m \^ 2) using the ratio of height to weight, ideally 18.5 to 24.9

-   Whether the beneficiary smokes

-   The beneficiary's residential area in the US, northeast, southeast, southwest, northwest.

-   Individual medical costs billed by health insurance

You can download the data [here](data/insurance_costs.csv)

# Step 2: Explore the Data

1.  Read in the dataset, and display some summaries of the data.

2.  Fix any concerns you have about the data.

::: callout-tip
# Data Type

Are the data types for all the variables what you want them to be?
:::

3.  Make up to three plots comparing the response variable (`charges`) to one of the predictor variables (e.g., `age`, `smoker`, `sex`, `bmi`, `region`). Briefly discuss what you notice in each plot (1-2 sentences per plot!).

::: callout-caution
# Professional Plots

1.  You are required to use [ggplot2](https://r4ds.had.co.nz/data-visualisation.html) to create your plots
2.  Every plot should have appropriately named axis labels (with units)
:::

# Step 3: Create (Simple) Models of the Data

4.  Fit a simple linear model to predict the insurance charges from the beneficiary's age.

5.  Interpret the coefficient estimates.

6.  Discuss the model fit, specifically the p-value associated with `age` and the model's $R^2$.

7.  Fit a model that also incorporates the variable `sex`.

8.  Provide interpretations for each of the coefficient estimates.

9.  Does it seem that the relationship between `age` and `cost` differs based on someone's `sex`? Why or why not?

10. How much additional variation in `cost` were we able to explain by adding `sex` into our model?

11. Now fit a model that does not include `sex`, but does include `smoker`.

12. Which model (`sex` or `smoker`) do you think better fits the data? Justify your answer by calculating the MSE for each model, and also by comparing R-squared values.

# Step 4: Create More Complex Models of the Data

Now let's consider including multiple *quantitative* predictors.

13. Fit a model that uses `age` and `bmi` as predictors.

::: callout-caution
# No interaction

Do not include an interaction term between `age` and `bmi`!
:::

14. Provide interpretations for each of the coefficient estimates.

15. How does the R-squared compare to the model with `smoker`?

16. How does the RMSE compare to the model with `smoker`?

::: callout-tip
# Calculate RMSE

Look back at this week's activity to remember how we calculated the RMSE of a model!
:::

17. Looking at the plot of `age` versus `charges` it seems like the relationship may not be linear! Fit a model that uses `age` and `age^2` as predictors (your model should not include `bmi`).

::: callout-tip
# Fitting a Polynomial

You can fit **both** the linear and quadratic terms using the following formula:

```{r}
#| eval: false
charges ~ poly(age, 2)
```
:::

18. How do the RMSE and R-squared compare to the model when we just used `age` (Step 3, Question 4)?

19. Let's get a little wigglier! Fit a polynomial model of degree 4. How do the MSE and R-squared compare to the model in (Step 3, Question 4)?

20. According to the MSE and R-squared, which is the best model? Do you agree that this is indeed the "best" model? Why or why not?

21. Plot the predictions from the model you believe is the best as a **line** plot on top of the scatterplot of your original data.

::: callout-warning
# Axis labels

Don't forget your axis labels and units (where needed)!
:::

# Step 5: Incorporate New Data

Great news! We've managed to collect data about the insurance costs for a few more individuals. You can find the new dataset [here](data/insurance_costs_2.csv).

Consider the following possible models:

-   Only `age` as a predictor.

-   `age` and `bmi` as a predictor.

-   `age`, `bmi`, and `smoker` as predictors (no interaction terms)

-   `age`, and `bmi`, with both quantitative variables having an interaction term with `smoker` (i.e. the formula `~ (age + bmi):smoker`)

-   `age`, `bmi`, and `smoker`as predictors, with both quantitative variables having an interaction term with `smoker` (i.e. the formula `~ (age + bmi)*smoker`)

22. For each model, *fit* the model on the **original data**.

23. For each model, use the fitted model to *predict* on the **new data**.

24. Report the MSE for each model's **new** predictions. Based on this, which is the best model to use?

25. Make a plot showing the residuals of your final chosen model.
