---
title: "Week 1 Reading Guide"
format:
  html:
    toc: true
  pdf:
    keep-tex: false
  docx:
    toc: false
prefer-html: true
embed-resources: true
editor: visual
---

## Chapter 2: Statistical Learning

1. **What is "reducible error" in statistical learning?**

2. **Can all error be taken out of a model predicting y? Why not?**

3. **What is the difference between inferential modeling and predictive modeling?**

4. **What are the differences between parametric and non-parametric models?**

5. **What are the advantages to using parametric methods? What are the disadvantages?**

6. **What is it called when a highly specific (flexible) model is fit to a training dataset?**

7. **What is the difference between supervised and unsupervised learning?**

8. **Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves on *one* plot.** 

The x-axis should represent the amount of flexibility in the method, and the y-axis should represent the values for each curve. There should be five total curves! Make sure to label each curve, so I know what it corresponds with.
