---
title: "Classification"
format: 
  html: 
    self-contained: true
    theme: minty
    fontsize: 1em
    mainfont: sans-serif
    number-sections: true
    number-depth: 2
    code-block-bg: "#76b5c5"
    highlight-style: monochrome
editor: source
execute: 
  echo: true
  eval: false
  include: false
---

This week we will focus on classification, using both parametric and nonparametric methods. We will break apart the chapter into two installments, starting with *simple* parametric methods (logistic regression), then moving to more *complex* parametric methods (linear discriminant analysis) and then nonparametric methods (KNN). 

# Logistic Regression

## Textbook Reading

📖 [**Required Reading:** *ISLR -- Chapter 4, Sections 4.1-4.3 Classification*](https://hastie.su.domains/ISLR2/ISLRv2_corrected_June_2023.pdf)

::: callout-warning
# Only Logistic Regression

Read pages 129 through 141, stopping after multinomial logistic regression. Also read section 4.6 on the applications of generalized linear models (pages 164 - 170). 
:::

## Logistic Regression Video 

Here's a helpful video which explains how logistic regression works: <https://youtu.be/yIYKR4sgzI8?si=h_gs42mR6YJ033gW>

## Concept Quiz -- Due Monday, October 9 at 2:10pm

Suppose we collect data for a group of students in an introductory  statistics class with variables X1 = hours studied, X2 = undergrad GPA, and Y = receive an A. We fit a logistic regression and produce estimated coefficients: $\widehat{\beta_0} = -6$; $\widehat{\beta_1} = 0.05$; $\widehat{\beta_2} = 1$.

**Question 1** -- The probability that a student who studies for 40-hours and has an undergrad GPA of 3.5 gets an A in their introductory statistics course is ___. (round to two decimal places)

**Question 2** -- For this student to have a 50% chance of getting an A in their course, they would need to study for ___ hours. (round to the nearest hour)

**Question 3** -- On average, if people have an odds of 0.37 of defaulting on their credit card payment,  ____ will actually default. (round to two decimal places)
 
 **Question 4** -- Suppose that an individual has a 16 % chance of defaulting on her credit card payment. The odds she will default is ____. (round to two decimal places)

# Generative Models

## Textbook Reading

📖 [**Required Reading:** *ISLR -- Chapter 4, Sections 4.4 & 4.5 5*](https://hastie.su.domains/ISLR2/ISLRv2_corrected_June_2023.pdf)

### Reading Guide -- Due Wednesday, October 4 at 2:10pm

📝 [Download the Word Document](reading-guide/week-3.docx)

## K-Nearest Neighbors Video 

Here's a helpful video which explains how k-Nearest-neighbors works with classification: <https://www.youtube.com/watch?v=HVXime0nQeI&ab_channel=StatQuestwithJoshStarmer>

::: {.callout-tip}
# Start at 2:43 for the section on classification!
:::

## Concept Quiz -- No quiz for this section, just the reading guide!

